// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB11CY6Cx7b_GuCYKvBfeQZ-GFJqjxh0u4',
    appId: '1:512134238452:web:0672e6af0267422d470ea1',
    messagingSenderId: '512134238452',
    projectId: 'chat-app-e6ca8',
    authDomain: 'chat-app-e6ca8.firebaseapp.com',
    storageBucket: 'chat-app-e6ca8.appspot.com',
    measurementId: 'G-BJ6K3HKRY9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsCXFxFQndyD9VafnZxdO0Cjgw7Gk6MkU',
    appId: '1:512134238452:android:cc0853b00b202281470ea1',
    messagingSenderId: '512134238452',
    projectId: 'chat-app-e6ca8',
    storageBucket: 'chat-app-e6ca8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrm7PF6E80970vkA6irQu2hnbBkn2VjAM',
    appId: '1:512134238452:ios:b2a9094a59d70686470ea1',
    messagingSenderId: '512134238452',
    projectId: 'chat-app-e6ca8',
    storageBucket: 'chat-app-e6ca8.appspot.com',
    iosBundleId: 'com.example.scholarChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrm7PF6E80970vkA6irQu2hnbBkn2VjAM',
    appId: '1:512134238452:ios:b2a9094a59d70686470ea1',
    messagingSenderId: '512134238452',
    projectId: 'chat-app-e6ca8',
    storageBucket: 'chat-app-e6ca8.appspot.com',
    iosBundleId: 'com.example.scholarChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB11CY6Cx7b_GuCYKvBfeQZ-GFJqjxh0u4',
    appId: '1:512134238452:web:2f8b694372f8e3df470ea1',
    messagingSenderId: '512134238452',
    projectId: 'chat-app-e6ca8',
    authDomain: 'chat-app-e6ca8.firebaseapp.com',
    storageBucket: 'chat-app-e6ca8.appspot.com',
    measurementId: 'G-RWF2TZ6DE0',
  );

}